blueprint:
  name: Enphase battery energy in kWh
  description: Enphase defaults to Wh, this converts to kWh
  domain: template
  input:
    battery_energy_wh:
      name: Source entity for battery capacity
      description: (ex. sensor.envoy_2_battery_capacity)
      selector:
        entity:
          domain: sensor

variables:
  original_entity: !input battery_energy_wh

sensor:
  state: >
    {{ states('original_entity') | float / 1000 }}
  unit_of_measurement: kWh
  device_class: energy
