blueprint:
  name: Set Battery Reserve From Production Forecast
  description: "Set battery reserve based on forecasted solar production. If forecast is smaller than battery capacity, set reserve to 100%."
  domain: automation
  input:
    energy_production_today:
      name: Forecasted Energy Production for Today
      description: Your forecasted energy production for today. Usually provided by forecast.solar.
      selector:
        target:
          entity:
            domain: sensor
    battery_capacity:
      name: Home Battery Capacity
      description: The entity for your battery capacity (ex. sensor.envoy_202347019745_battery) in kWh (important!). You can either edit the unit to kWh and change precision or use a tempalate sensor.
      selector:
        target:
          entity:
            domain: sensor
    battery:
      name: Battery device
      description: Your battery device (ex. Enpower)
      selector:
        target:
          device:
    reserve_level:
      name: Battery reserve level
      description: The entity controlling your battery reserve (ex. number.enpower_202348002500_reserve_battery_level)
      selector:
        target:
          entity:
            domain: number

triggers:
  - trigger: time
    at: "06:55:00"

variables:
  batt_cap: !input battery_capacity

actions:
  - if:
      - condition: numeric_state
        entity_id: !input energy_production_today
        above: >
          {{ states('batt_cap') | float / 1000 }}
    then:
      - device_id: !input battery
        domain: number
        entity_id: !input reserve_level
        type: set_value
        value: 40
    else:
      - device_id: !input battery
        domain: number
        entity_id: !input reserve_level
        type: set_value
        value: 100
mode: single
